# Generated by Django 2.2.4 on 2022-10-06 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_trees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trees',
            name='addedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='exam.User'),
        ),
    ]
